# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [2]:
#1 
import numpy as np
[[[k]]]

arr = np.loadtxt('data/minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
print(arr[0:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [281]:
#2
print(f'''
                                  I           II
Среднее значение cтолбца   | {float(np.mean(arr[:, 1:2], axis=0))} | {float(np.mean(arr[:, -1], axis=0))} |
Минимальное значение       | {int(arr[:, 1:2].min(axis=0))}           | {int(arr[:, -1].min(axis=0))}       |
Максимальное значение      | {int(arr[:, 1:2].max(axis=0))}  | {int(arr[:, -1].max(axis=0))}      |
Медиана столбца            | {int(np.median(arr[:, 1:2], axis=0))}          | {int(np.median(arr[:, -1], axis=0))}       |
''')


                                  I           II
Среднее значение cтолбца   | 21601.00169 | 9.05528 |
Минимальное значение       | 0           | 1       |
Максимальное значение      | 2147483647  | 39      |
Медиана столбца            | 40          | 9       |



In [393]:
#3
q = int(np.quantile(arr[:, 1:2], 0.75, axis=0))

new_arr = arr[:,1:2]
new_arr[new_arr > q] = q
print(arr[:, 1:2])

[[60]
 [25]
 [10]
 ...
 [65]
 [ 5]
 [65]]


In [394]:
#4
print(int(np.sum(arr[:, 1:2] == 0)))
new_arr[new_arr == 0] = 1
print(int(np.sum(arr[:, 1:2] == 0)))

479
0


In [395]:
#5
print(len(np.unique(arr[:, 0:1])))

100000


In [396]:
#6
unique, counts = np.unique(arr[:,-1], return_counts= True)
print(np.asarray((unique, counts)).T)

[[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


In [397]:
#7
less_minutes = arr.copy()
less_minutes = less_minutes[less_minutes[:, -1] <= 5]
print(less_minutes, len(less_minutes))

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]] 17262


In [398]:
#8
print((less_minutes[:, 1] / less_minutes[:, 2]).max())

65.0


In [399]:
#9
newmass = arr.copy();
newmass = newmass[np.argsort(newmass[:, 1])]
print(np.mean(newmass[-101:-1, 2]))

9.9


In [400]:
#10
import random
for i in range(10):
    print(arr[random.randint(0, len(arr[:, -1]))])

[191186     45      9]
[154473     65      7]
[10050    65     7]
[275886     55      9]
[393750     45     14]
[319550     65     11]
[140361     40     15]
[285492     40      6]
[267297     65      9]
[133279     65     11]


In [417]:
#11
len(arr[arr[:, 2] < np.mean(arr[:, 2])]) / len(arr[:,0]) * 100

58.802

In [134]:
#12
new_data = arr.copy()
easy_receips = new_data[new_data[:, 1] <= 20]
easy_receips = easy_receips[easy_receips[:, 2] <= 5]
mask = np.in1d(new_data[:, 0], easy_receips[:, 0])
mask = np.where(mask, 1,0)
mask = np.reshape(mask, (mask.shape[0], 1))
new_data = np.append(new_data, mask, axis=1)
print(new_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


In [142]:
#13
print(len(new_data[new_data[:, -1] == 1])/len(new_data[:, -1])*100)

9.552


In [154]:
new_data2 = arr.copy()
easy = new_data2[new_data2[:, 1] <= 10]
medium = new_data2[(new_data2[:, 1] > 10) & (new_data2[:, 1] < 20)]
hard = new_data2[(new_data2[:, 1] >= 20)]
min_shape = min(easy.shape[0], medium.shape[0], hard.shape[0])
three_dim = np.stack((easy[:min_shape], medium[:min_shape], hard[:min_shape]))
print(three_dim)

[[[ 94746     10      6]
  [ 67660      5      6]
  [366174      7      9]
  ...
  [  7983      0      6]
  [184171      5      2]
  [ 89181      5      7]]

 [[ 33941     18      9]
  [446597     15      5]
  [ 81006     12      7]
  ...
  [ 44120     17      5]
  [ 60756     15      5]
  [128811     15      4]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [186515    220     11]
  [372540     50      6]
  [172926    120     13]]]
